<!DOCTYPE html>
<html>
	<head>
		<title><?=$this->title?></title>
		<link rel="stylesheet" type="text/css" href="//<?=APP_ROOT?>public/css/shared/error.css">
		<link rel="stylesheet" type="text/css" href="//<?=APP_ROOT?>public/vendor/icomoon/style.css">

		<script type="text/javascript" src="//<?=APP_ROOT?>public/vendor/jquery/jquery-3.2.1.min.js"></script>
		<script type="text/javascript" src="//<?=APP_ROOT?>public/vendor/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>
	</head>
	<body>

		<div title-error>404 - Página não encontrada</div>
		<a href="./">
			<button>
				Clique aqui para voltar a home page
			</button>
		</a>

	</body>
</html>